spring:
   datasource:
     url: jdbc:h2:mem:test # h2 support in-memory-db
     driver-class-name: org.h2.Driver
   jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
   
   h2:
    console: 
      enabled: true
        
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace