INSERT INTO post (title, content, created_at, updated_at) VALUES ('김민지', '최고', NOW(), NOW())
INSERT INTO post (title, content, created_at, updated_at) VALUES ('강해린', '최고', NOW(), NOW())
INSERT INTO post (title, content, created_at, updated_at) VALUES ('팜하니', '최고', NOW(), NOW())
INSERT INTO reply (content, post_id, created_at, updated_at) VALUES ('ㄹㅇㅋㅋ', 1, NOW(), NOW())
INSERT INTO reply (content, post_id, created_at, updated_at) VALUES ('ㅋㅋㅋㅇㅈ', 1, NOW(), NOW())
INSERT INTO reply (content, post_id, created_at, updated_at) VALUES ('ㅇㅈㅋㅋ', 2, NOW(), NOW())